### ISSUE TITLE
Can't get past "start" screen

### ISSUE THREAD

**Issue by Gpar2023** [coolguyunblocked/Intellistar-2-XD-Emulator#5]
I typed my ZIP code and pressed "Start," but it didn't work. I added the crawl and the greeting text, but it still doesn't work. I checked that my ZIP code is correct and tried again, but it's still not working. **Sorry for the long description.** :/

**Comment by Halloween20** [comment]
do know when is going to be fixed ?

**Comment by Gpar2023** [comment]
No I don't know but it might take a while because the creator hasn't contributed anything since January? :(
